
allowBuilds:
  '@parcel/watcher': false
  
packages:
  - "example/*"
  - "internal/*"
  - "packages/*"
  - "apps/*"

overrides:
  "x-zxing-js-library": "npm:empty-module@^0.0.2"
  "@x-apaas/x-apaas-frontend-i18n": "3.2.20-lts.20240119.2.2026"
  "@x-apaas/x-dcloud-page-engine": "3.2.20-lts.20240119.2.2242"
  "@x-apaas/x-dcloud-business-event": "3.2.20-lts.20240119.2.2137"
  "@x-apaas/x-lib-rule-engine": "npm:empty-module@^0.0.2"

